title: "Interview Docs"
remote_theme: pmarsceill/just-the-docs
# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

search_enabled: false

theme: jekyll-theme-minimal